### ISSUE TITLE
XenRealBattery widget not working on v2

### ISSUE THREAD

**Issue by Potterd** [Matchstic/Xen-HTML#266] opened 2020-06-02 06:18 UTC
**Describe the bug**

On LS / background Always displays 69%

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 11.1.2]

**Additional context**
Add any other context about the problem here, such as a link to a crash log.

**Comment by Potterd** [comment] 2020-06-03 07:40
I have found additional “Battery” widgets that display 69% on v2, and work correctly with v1 and Infostats / Xeninfo

**Comment by Matchstic** [comment] 2020-06-03 12:52
Cannot reproduce this issue; XenRealBattery appears correct, even after a respring.
It's likely you may be seeing old cached battery data, indicating an issue occurred when talking to widgetinfod.

Does a respring/ldrestart help?

**Comment by Starshooter1996** [comment] 2020-06-03 18:14
I also had trouble with the default widgets, but a full reboot and jailbreakig again seemed to fix it. Took a long time for the data to show but it works! Battery just doesn't show Estimated time only says "No Information" but keep up the great work excited to see this implemented in Xen HTML now, been using this tweak every since it was first released back in the days.

**Comment by Matchstic** [comment] 2020-06-04 01:11
Closing in favour of tracking this issue in #270

**Closed by Matchstic** 2020-06-04 01:11 UTC
