### ISSUE TITLE
Fullscreen notifications not working

### ISSUE THREAD

**Issue by Zane-** [Matchstic/Xen-HTML#87] opened 2019-03-20 16:43 UTC
When I have fullscreen notifications, the notifications start a couple hundred pixels from the top. Here is a list of my installed tweaks: https://pastebin.com/hk17A5wz
## Example:
<img src="https://i.imgur.com/y1hVD7a.jpg" width="50%" height="50%" title="Example">

**Comment by Matchstic** [comment] 2019-03-21 22:39
Can you confirm that this isn't being caused by MiDevice or NCNoTitle please? Fullscreen notifications are working just fine on my end.

**Comment by Zane-** [comment] 2019-03-21 22:45
> Can you confirm that this isn't being caused by MiDevice or NCNoTitle please? Fullscreen notifications are working just fine on my end.

I've tried disabling both separately/together and the issue still persists.

**Comment by Matchstic** [comment] 2019-03-22 21:41
Great, thanks for looking into it!

**Comment by Matchstic** [comment] 2019-07-14 09:34
Closing due to not being caused by Xen HTML

**Closed by Matchstic** 2019-07-14 09:34 UTC
