### ISSUE TITLE
Buttons won’t work after second click

### ISSUE THREAD

**Issue by johnson033** [Matchstic/Xen-HTML#198] opened 2020-02-28 08:25 UTC
[weather.zip](https://github.com/Matchstic/Xen-HTML/files/4266014/weather.zip)
I’m making a widget with a button to switch between weather and then a music controller. When I press a button it is suppose to switch. It works fine the first time but when I want to go back to weather it won’t let me. I know my code is fine, it works fine on my computer and when I load up the page from filza. Idk what the issue could be but any ideas would be appreciated.
PS. Ive also attached a link at the top for the Widget itself if it is useful to help figure out the issue.

**Comment by Matchstic** [comment] 2020-02-28 16:21
My only thought its that in Xen HTML, you'd have mainUpdate() called by XenInfo, which doesn't happen in e.g. Filza. Make sure to check the widget with the dylib for XenInfo disabled. If that works, then the issue isn't with Xen HTML

**Comment by johnson033** [comment] 2020-02-28 17:24
You where correct. It seems that Xen info is causing the issue.

**Comment by Matchstic** [comment] 2020-02-29 21:34
Ah good that it’s tracked down a little. I’ll close this ticket as a result

**Closed by Matchstic** 2020-02-29 21:34 UTC
