### ISSUE TITLE
Unwanted resprings

### ISSUE THREAD

**Issue by puzzledyt** [Matchstic/Xen-HTML#108] opened 2019-05-09 16:59 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 11.1.2]

**Additional context**

**Comment by puzzledyt** [comment] 2019-05-09 17:01
When on the home screen (iPhone XR) if I swipe up to get to multi-tasking it will respring only if I swipe from the very very bottom of the screen but still happens when I don’t want it too I’m new to jailbreaking so can’t fidn a way to fix this could it be a conflicting tweak? Or simply a bug

**Comment by Matchstic** [comment] 2019-05-30 20:22
I've not heard of anyone else experiencing this issue. Does removing Xen HTML help?

**Comment by Matchstic** [comment] 2019-07-27 20:39
No feedback, so closing this issue. Likely caused by a tweak conflict!

**Closed** 2019-07-27 20:40 UTC
Labels: bug, needsfeedback
