### ISSUE TITLE
Imcompatibility with password on lockscreen

### ISSUE THREAD

**Issue by Alolu** [Matchstic/Xen-HTML#168] opened 2019-12-26 21:00 UTC
Hi,

The bug: 
If you install Xen-HTML while having a password, you can't see anything of the setup and can't do anything with the Iphone until you restart the jailbreak in safe mode
Furthermore, if you reactivate your password afterwards, while your device will work as usual, the lockscreen widgets won't work until you disable your password again

1. Enable password
2. Install Xen-HTML
3. Respring
4. You can't do anything
Or if you managed to pass the setup:
1. Enable your password
2. Add a widget to the lockscreen
3. Respring
4. No widgets at all

Expected behavior: 
The setup and widgets should work without having to disable your password

 - Device: tested on Iphone 7 and Iphone 8
 - OS: iOS 13.3

/User/XenHTMLWebGLDebug.txt: 
`(WebGL.xm40) DEBUG ::
CA::Render::Context::process_name is NOT a valid pointer
`

**Comment by Matchstic** [comment] 2019-12-28 22:25
Duplicate of #156

**Closed by Matchstic** 2019-12-28 22:25 UTC
