### ISSUE TITLE
Lock screen don’t show up on iPhone 7+. On ios13

### ISSUE THREAD

**Issue by germanicon** [Matchstic/Xen-HTML#152] opened 2019-11-15 06:54 UTC
**Describe the bug**
Won’t work on lock screen. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 11.1.2]

**Additional context**
Add any other context about the problem here, such as a link to a crash log.

**Comment by Matchstic** [comment] 2019-11-16 12:07
Duplicate of #150

**Closed by Matchstic** 2019-11-16 12:07 UTC
