### ISSUE TITLE
Once XenHTML installed freezes the lockscreen after ldrestart and needed rejailbreak and remove it .11 pro device,13.2.2 iOS.

### ISSUE THREAD

**Issue by yiannko** [Matchstic/Xen-HTML#217] opened 2020-04-06 09:57 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 11.1.2]

**Additional context**
Add any other context about the problem here, such as a link to a crash log.

**Comment by Matchstic** [comment] 2020-04-06 10:01
Duplicate of #216

**Closed by Matchstic** 2020-04-06 10:01 UTC
