### ISSUE TITLE
LS Freezes with XenHTML enabled

### ISSUE THREAD

**Issue by Potterd** [Matchstic/Xen-HTML#216] opened 2020-04-05 23:10 UTC
**Describe the bug**

iPhone SE on iOS 13.3.1 and iOS 13.4 (2 devices): When LS is accessed, intermittent freeze occurs for 45-60 sec and then device resprings.  The freeze appears to time out.  Happens when the LS is accessed from wake, respring, after Cydia install or when accessing Notification Center.  Problem is intermittent and occurs numerous times throughout the day on both devices.  Problem does not occur if Xen HTML is disabled.

See additional bug reports: 179, 186 (I previously added comments to these reports) and 211.

Please let me know if I can be of any assistance resolving this problem (testing or to provide additional information) - The issue occurs regularly on my devices.
 
**To Reproduce**
Occurs intermittently during normal usage.

**Expected behavior**
No freezing

**Screenshots**

**Smartphone (please complete the following information):**
 - iPhone SE, iOS 13.3.1
-  iPhone SE, iOS 13.4

**Additional context**
Add any other context about the problem here, such as a link to a crash log.

**Comment by Matchstic** [comment] 2020-04-06 11:03
Do you also have XenInfo installed? If so, please try disabling that and observe the effects.

**Comment by Potterd** [comment] 2020-04-06 16:26
I have tested with Xeninfo disabled and removed and continued to observe the issue but that testing was a couple of weeks ago - will retest today by removing Xeninfo from both devices and let you know the results.

**Comment by Potterd** [comment] 2020-04-07 07:32
Removing Xeninfo from both devices, the problem still occurs.  After removing Xen HTML, the problem no longer occurs.  Removing just the weather widget with Xen HTML and Xeninfo installed and the problem still occurs.  I want to emphasize that this usually happens after a respring and can be triggered intermittently by CC, Cosette, Cydia, Springtomize and any  other apps that respring, and can also be triggered by accessing the Notification Center.  And it is always triggered by LDRestart (not internittent with LDRestart).  In fact after LDRestart the screen freezes for 60 sec, then respring occurs, then it freezes again for 60 sec and then a 2nd respring occurs before it is possible to complete the passcode entry.  Frozen screen is usually the passcode entry screen due to the fact that this is the landing page for respring / LDRestart.  The freeze is always very close to 60 sec, so it appears that some timeout is involved.  Due to the way it is occurring, it seems that it has be either Checkra1n or Xen HTML.  I use different versions of Checkra1n for the two devices due to the fact that they are on different iOS 13.x versions and I have not heard of any freezes associated with Checkra1n.

I would be happy to test your new Xen HTML 2 version at some point to determine if this issue is present in the new version.  If you want to send me a copy to test, you can use the link below to upload to a Dropbox folder.  Since my LDRestart test triggers the behavior every time, I can quickly test for this problem and get back to you.

https://www.dropbox.com/request/7DyFQe0pMiqcQfxigTuf

Regards ..... David Potter

**Comment by Matchstic** [comment] 2020-04-19 15:01
Xen HTML 2 would still have the same issue, since that is mainly just adding a new dylib for widget data!

Can you try disabling tweaks in sequence (with the exception of Xen HTML) with iCleaner, and then seeing at what point the issue doesn't occur?

This is the sort of bug that should happen to every user if Xen HTML is the cause. By the sound of it, it is a tweak causing a conflict somewhere.

**Comment by Potterd** [comment] 2020-04-19 17:17
Difficult since the freezes are intermittent, most likely conflict is Xeninfo.  Also occurs most of the time after respring triggered by Cydia install.  I have spent considerable time trying to isolate this and it keeps coming back to removing Xen HTML, Xeninfo or Widget as a way to fix.

If you are able to share a pre-release version of Xen HTM 2, I can simply install and wait 24hrs to see if removing Xeninfo resolves the issue.  

Upload link: 
https://www.dropbox.com/request/7DyFQe0pMiqcQfxigTuf

Regards,

David Potter
DPotter Consulting Inc
(415) 485-5876 (office)
(415) 608-7797 (mobile)
David@dpotterconsulting. com

You can view me on LinkedIn: www.linkedin.com/in/dpotterconsulting

**Comment by Matchstic** [comment] 2020-04-19 19:51
Thanks for the offer, but I'm not able to send you a pre-release version. It'll be best if we revisit this issue when the first beta of Xen HTML 2 is made public.

**Comment by Potterd** [comment] 2020-04-19 20:44
No problem, I’m doing more testing now and I have a prime suspect identified.  Will Let know in a day or so if I have the culprit ☠️

Appreciate your work !

Regards,

David Potter
DPotter Consulting Inc
(415) 485-5876 (office)
(415) 608-7797 (mobile)
David@dpotterconsulting. com

You can view me on LinkedIn: www.linkedin.com/in/dpotterconsulting

**Comment by Potterd** [comment] 2020-04-21 02:09
I have completed a thorough review of my entire package list (160 packages) and identified the conflicts.  To clarify, the problem causes intermittent freezes after respring on the LS and causes a freeze 100% of the time at the end of the Checkra1n JB.  So performing the Checkra1n JB is the most efficient way to test since the problem occurs 100% of the time.  However, this method is time consuming.  The freeze times out after approx 60 sec and generates another respring which may or may not result in another freeze.

The problem occurs on my devices when Xen HTML is installed and one or more of the following 3 packages is also installed: Modernbarz, StatusbarBGs, Color Switch.  I suspect that there are additional packages that will trigger this conflict but these are the ones that cause the issue on my devices.  When either Xen HTML is removed, or all of the other packages are removed, the freezing does not occur.  If Xen HTML and one or more of the 3 packages listed above are installed the freeze occurs at the end of every Checkra1n JB or intermittently following resprings, with the Cydia respring having a higher probability of causing the problem than other types of resprings.

As a reminder my devices are iPhone SE running iOS 13.4.1 using Checkra1n v0.10.1.

This should be fairly easy for you to reproduce - let me know if you have questions or need additional information.  If you don't want to bother testing with Checkra1n, you could consider just installing the free StatusbarBGs tweak from "i0s-tweak3r-betas.yourepo.com" and just continue with your normal testing as I suspect you will soon start to experience these freezes.

This issue is extremely annoying so I hope you will be able to resolve at some point.

**Comment by Potterd** [comment] 2020-04-21 20:23
After additional test suggested by @BrianVS (author of ModernBarz and StatusbarBGs) I have found that: ‪Yes, turning of LS switch in Xen HTML or disabling Xen HTML in iCleaner are both effective to avoid the freeze during JB with Checkra1n.

**Comment by Tweaker177** [comment] 2020-04-22 20:07
I’m going to add the StatusBarBGs to my GitHub later. I did some code cleanup and made some changes to reduce CPU use, and sent a build to David. Going to try a couple more changes to see if that makes a difference before adding it to GitHub. 

 Otherwise, there’s a good chance the tweak could be re-written to use SpringBoard as the filter (but still work system wide) instead of UIKit; if that works I’d think that should help immensely. 

I have a feeling the core of the issue is the total CPU useage when SB is loaded, not that the tweaks conflict.

**Comment by Potterd** [comment] 2020-04-27 00:15
Due to great work by Tweaker177 (author of StatusbarBGs) who has produced a new version of StatusbarBGs that no longer causes the LS freezes that I have been experiencing for several weeks now.  Very grateful to you both for maintaining an open communication channel regarding this issue.  Special thanks to Tweaker177 for the great support in helping to resolve this annoying problem.

**Comment by Matchstic** [comment] 2020-05-22 21:09
Re-opening this issue to track progress.

From a second report, I have noticed that tweaks exhibiting this issue all make use of HBPreferences from libcephei.

**Comment by Matchstic** [comment] 2020-05-23 14:03
I believe this is now fixed by commit f7d9a35db7a0534fb7a36be280701090d5082b4f

The change was to add a new dylib on my end, that denys accidental injection into com.apple.WebKit.* XPC services.

**Comment by Matchstic** [comment] 2020-05-25 16:09
Closing, since this issue appears fixed for the most part

**Closed by Matchstic** 2020-05-25 16:09 UTC
