### ISSUE TITLE
Lock screen bug

### ISSUE THREAD

**Issue by ipaduser1** [Matchstic/Xen-HTML#207] opened 2020-03-15 11:12 UTC
Its a little bug that I do find very annoying it a glitch with the widgetS on the lock screen that if you swipe to your camera it makes the side of the screen black

Steps to reproduce the:
1. Swipe left on the lock screen

Just to fix the bug so it doesn’t get in my way

**Smartphone (please complete the following information):**
 - Device: iPad 6th Gen
 - OS: 13.1.2

**Comment by Matchstic** [comment] 2020-04-19 15:06
Duplicate of #117

**Closed by Matchstic** 2020-04-19 15:06 UTC
