### ISSUE TITLE
Haptic Feedback on EventListeners

### ISSUE THREAD

**Issue by paraskcd1315** [Matchstic/Xen-HTML#325] opened 2021-02-24 03:50 UTC
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An option to invoke iPhone's taptic engine contained in a function that requires you to add a small Timeout duration or something to keep the Vibrating motors going. Somewhat like how Android implements it in their chromium based browsers, with window.navigator.vibrate(). There's no way to do it through webkit.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate site contains information how the vibrate works in Android devices.

**Comment by Matchstic** [comment] 2021-02-24 09:08
Duplicate of https://github.com/Matchstic/libwidgetinfo/issues/47

**Closed as completed by Matchstic** 2021-02-24 09:08 UTC
