### ISSUE TITLE
Touch does not work on the lock screen after respring.

### ISSUE THREAD

**Issue by Minj-0726** [Matchstic/Xen-HTML#201] opened 2020-03-07 06:03 UTC
The touch function does not work on the lock screen.
And physical keys don't respond either.

It resprings automatically when left alone.
Generally, it will operate normally after repeated several times.

xs 13.3 unc0ver v4.2.1

**Comment by Matchstic** [comment] 2020-04-19 15:02
Cannot reproduce this issue. Likely a duplicate of #216

**Closed by Matchstic** 2020-04-19 15:02 UTC
