### ISSUE TITLE
[Crash] When clicking Lockscreen (reset/reinstall didn’t help)

### ISSUE THREAD

**Issue by Oxtie** [Matchstic/Xen-HTML#187] opened 2020-02-22 07:17 UTC
**Describe the bug**
I put a widget on lock screen’s background section. I’m on i7+ (iOS 13.3.1 with Checkra1n 0.9.8).

Earlier, I was going into freeze and boot loops and when I disabled XenHTML, all became normal 🤔 Before when I set widget to Foreground, settings app didn’t crash. 

**To Reproduce**
1. Go to Settings
2. Click on XenHTML
3. Click Lockscreen
4. See Settings app Crash

**Expected behavior**
After respring, I seedelay in widget showing up (7 seconds) which is Not normal, I expected 1 second delay 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS 13.3.1

**Additional context**
I also have “Time“ tweak installed 🤔 this is the only conflicting possibility

**Comment by Matchstic** [comment] 2020-04-19 15:07
For the settings crash, this is probably a duplicate of #221

**Closed by Matchstic** 2020-04-19 15:07 UTC
