### ISSUE TITLE
Widget moving when double tapping

### ISSUE THREAD

**Issue by ras989** [Matchstic/Xen-HTML#292] opened 2020-06-15 14:44 UTC
Fuji forever, in foreground lockscreen moving around when double tap the widget
![C0BE4D56-3824-4341-A150-6A1AB337F031](https://user-images.githubusercontent.com/66359554/84671297-8d493200-af6a-11ea-86b1-53795d808b73.png)

**Comment by Matchstic** [comment] 2020-06-15 14:47
Duplicate of #233

**Closed by Matchstic** 2020-06-15 14:47 UTC
