### ISSUE TITLE
Settings App Crashes

### ISSUE THREAD

**Issue by Gwarion** [Matchstic/Xen-HTML#47] opened 2018-07-20 03:08 UTC
iOS 10.2 on 6s+
Jailbroken with double helix.

The settings App crashes when I select "homesceen" in Xen HTML settings 

Edit : video
https://youtu.be/DOEA7x9NH10

Also sent you the crash report through crash reporter at you @incendo.ws address

**Comment by Gwarion** [comment] 2018-07-20 03:13
Here's a video https://youtu.be/SGvor-CgqFE and I sent you the crash report through crash reporters to your adress @incendo.ws

**Comment by Matchstic** [comment] 2018-08-28 19:37
Duplicate of #45

**Closed by Matchstic** 2018-08-28 19:37 UTC
Labels: bug
