### ISSUE TITLE
Phone freezes after a respring 

### ISSUE THREAD

**Issue by antherkill** [Matchstic/Xen-HTML#186] opened 2020-02-20 14:59 UTC
After respringing my device(either tweak installation or to save changes), the lockscreen freezes and I can’t use my phone I can quickly unlock where the phone just freezes for a minute and resprings and it does this in a loop (you can hard restart it to make it boot into normal iOS)

iPhone 8 IOS 13.3 Jailbroken using checkra1n 

To repeat this have a widget installed in with Xenhtml in either lock screen or home screen and respring

There is no crash log produced.

**Comment by Matchstic** [comment] 2020-02-26 08:56
Can not reproduce. How many widgets do you have enabled?

**Comment by Potterd** [comment] 2020-03-13 22:53
I am also having this issue with Checkra1n on iOS 13.3.1.  Freezes with a respring after 60 seconds after JB and after some resprings and as described in this issue.  If I disable LS in Xenhtml, the issue does not occur.  There are no crash dumps.

**Comment by Potterd** [comment] 2020-03-13 23:01
Occurs on every JB on my device so is easy to reproduce - Will be happy to assist with testing the fix if you decide to work on it (would be nice to eliminate this nuisance issue).

**Comment by Potterd** [comment] 2020-03-13 23:19
The problem I am experiencing is resolved if I remove the Weather12 widget.  This widget displays weather information so it uses Xeninfo.  It works fine and displays the weather data correctly but appears to create the issue described above.  I am aware that Xeninfo has existing problems that have been reported and has not been updated for iOS 13, and also aware that you are working on a replacement and/or integration with Xenhtml.

**Comment by Matchstic** [comment] 2020-04-19 15:08
Likely a duplicate of #216. 

Since it seems the issue is caused by XenInfo, the good news is that I'm not far away now for a beta of Xen HTML that removes the need for it

**Closed by Matchstic** 2020-04-19 15:08 UTC
