### ISSUE TITLE
Stuck on lockscreen after respring

### ISSUE THREAD

**Issue by NinjaBG** [Matchstic/Xen-HTML#179] opened 2020-02-17 15:21 UTC
After respringing my device(either tweak installation or to save changes), the lockscreen freezes and I can’t use my phone until a second respring, caused by system crash. While it’s frozen, all custom widgets don’t show up, only Apple’s default camera/flashlight toggles

Respring

 - Device: iPhone X
 - OS: 13.3

**Comment by Potterd** [comment] 2020-03-13 22:55
I am also having a similar issue with Checkra1n on iOS 13.3.1.  Freezes with a respring after 60 seconds after JB and after some resprings and as described in this issue and in issue #186.  If I disable LS in Xenhtml, the issue does not occur.  There are no crash dumps.

**Comment by Potterd** [comment] 2020-03-13 23:01
Occurs on every JB on my device so is easy to reproduce - Will be happy to assist with testing the fix if you decide to work on it (would be nice to eliminate this nuisance issue).

**Comment by Potterd** [comment] 2020-03-13 23:20
The problem I am experiencing is resolved if I remove the Weather12 widget.  This widget displays weather information so it uses Xeninfo.  It works fine and displays the weather data correctly but appears to create the issue described above.  I am aware that Xeninfo has existing problems that have been reported and has not been updated for iOS 13, and also aware that you are working on a replacement and/or integration with Xenhtml.

**Comment by Matchstic** [comment] 2020-04-19 15:09
Likely a duplicate of #216.

**Closed by Matchstic** 2020-04-19 15:09 UTC
