### ISSUE TITLE
On ios 13 XenHTML crashing

### ISSUE THREAD

**Issue by Zippas** [Matchstic/Xen-HTML#153] opened 2019-11-17 10:44 UTC
When Im installing the XenHTML tweek the phone reboot itself to a safe mode... After deleting the XenHTML the phone works fine again.
IOS 13.3 Iphone X

**Comment by Matchstic** [comment] 2019-11-20 10:13
Duplicate of #150

**Closed by Matchstic** 2019-11-20 10:13 UTC
