### ISSUE TITLE
Phone freezes after reboot or ldrestart

### ISSUE THREAD

**Issue by djoma99** [Matchstic/Xen-HTML#328] opened 2021-03-04 23:50 UTC
When XenHTML is enabled and I reboot my phone and jailbreak again or when I do ldrestart my phone freezes for about 60 seconds and then resprings.If I have widget on lockscreen it happens once but if I have widget on both lockscreen and homescreen it happens twice (in a row).I can confirm that this is happening because of XenHTML because when I disable it with iCleanerPro problem is not occurring.

And all that happend all of a sudden it was working fine until beta 7.1 got released,and now even if I downgrade problem is still occurring.
I tried disabling XenInfo too but that didn’t fix the problem.

**System Info**

- Device: [iPhone Xr]
- OS: [iOS 14.3]
- Xen HTML version: [e.g. 2.0~beta7.1]

There’s no crash log in Cr4shed.

PS: This is not happening after normal respring.

**Comment by Matchstic** [comment] 2021-03-05 12:11
I’ve been speaking to another user about this, and they narrowed the problem down to an incompatibility with Genesis 2. Please can you confirm if this is a tweak you are using?

**Comment by PortalRex** [comment] 2021-03-07 19:56
I am also having the exact same problem, disabling XenHTML through iCleaner fixes the problem. I do not have Genesis 2 downloaded.

**Comment by Matchstic** [comment] 2021-03-07 19:59
@PortalRex Its very likely to be a tweak conflict in this case. Please can you try disabling all other tweaks except the XenHTML dylibs, and gradually re-enable them until the issue occurs.

**Comment by Matchstic** [comment] 2021-03-07 20:11
For my own sanity, I'm linking this to ticket: https://github.com/Matchstic/Xen-HTML/issues/216

A year or so ago, there was an issue where if another tweak is injecting into ANY UIKit-loading process, this lead to freezes similar to this. On iOS 14, I have disabled my workaround to the problem, with the understanding that Substitute etc now apply the workaround to this automatically. 

This works fine on checkra1n, but after seeing comments from other developers, this mechanism might not be working under unc0ver. Could be related.

My initial investigation showed that tweaks exhibiting this problem were also reliant on libcephei. Its not a bug in libcephei, but an unfortunate side effect. So far, I'm aware that Genesis 2 also has this setup.

I'm very interested to see if other tweaks lead to this problem.

**Comment by PortalRex** [comment] 2021-03-07 20:42
Ok so I have narrowed the problem down to [Boardy](https://chariz.com/buy/boardy)

**Comment by Matchstic** [comment] 2021-03-07 22:15
@PortalRex thanks, that also fits my post above. It looks like Boardy relies on libcephei too, and likely injects into all UIKit processes.

**Comment by Matchstic** [comment] 2021-03-07 23:39
@PortalRex Please can you try this build of Xen HTML, and re-enable Boardy.

https://www.dropbox.com/s/g4xmuqncvw0r6sl/com.matchstic.xenhtml_2.0~beta8.4_iphoneos-arm.deb?dl=0

I have re-enabled my workaround, but only to block injection into processes that contain "com.apple.WebKit" in their name. It should be specific enough to not cause any problems.

**Comment by PortalRex** [comment] 2021-03-07 23:46
Sadly the problem persists.

**Comment by Matchstic** [comment] 2021-03-08 16:21
@PortalRex Another one to test please: https://www.dropbox.com/s/h2m0slieb5r3ox7/com.matchstic.xenhtml_2.0~beta8.18_iphoneos-arm.deb?dl=0

**Comment by PortalRex** [comment] 2021-03-08 16:24
This one works! ldrestart does not cause a freeze anymore!

**Comment by Matchstic** [comment] 2021-03-08 16:27
Excellent news!

I’m going to leave this ticket open until the final v2.0 is released to the public. If any else has this problem, please feel free to install the build I posted in my previous comment.

**Comment by djoma99** [comment] 2021-03-08 20:31
@Matchstic Sorry I wasn’t replying I wasn’t getting notifications from github.Thank you for replying though and for this deb file.It fixed it!!

**Comment by Matchstic** [comment] 2021-03-14 19:12
Closing this now because beta 9 is available, which includes the relevant fix

**Closed as completed by Matchstic** 2021-03-14 19:12 UTC
Labels: needsfeedback
